import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  applicant: DS.attr('string'),
  applicantdescription: DS.attr('string'),
  referrerorganization: DS.attr('string'),
  referrercontact: DS.attr('string'),
  description: DS.attr('string'),
  socialgoals: DS.attr('string'),
  activities: DS.attr('string'),
  geofocus: DS.attr('string'),
  laws: DS.attr('string'),
  whistleblowingtype: DS.attr('string'),
  motivations: DS.attr('string'),
  partners: DS.attr('string'),
  board: DS.attr('string'),
  communication: DS.attr('string'),
  information: DS.attr('string'),
  usage: DS.attr('string'),
  dependency: DS.attr('string'),
  sustain: DS.attr('string'),
  url: DS.attr('string'),
  user: DS.belongsTo('user'),
  recipient: DS.attr('string'),
  contact: DS.attr('string'),
  value: DS.attr('number'),
  realvalue: DS.attr('number'),
  starts: DS.attr('isodate'),
  finished: DS.attr('number'),
  ended: DS.attr('boolean'),
  accepted: DS.attr('boolean'),
  moderated: DS.attr('boolean'),
  votes: DS.attr('number'),
  vetos: DS.attr('number'),
  spamanswer: DS.attr('string')
});
